export const RETRIEVE_STORE_DETAIL_SUCCESSFULLY =
  'RETRIEVE_STORE_DETAIL_SUCCESSFULLY';
export const RETRIEVE_STORE_DETAIL_FAILED = 'RETRIEVE_STORE_DETAIL_FAILED';

export const SET_CURRENT_SHOP = 'SET_CURRENT_SHOP';
