export const CREATE_STORE_SUCCESSFULLY = 'CREATE_STORE_SUCCESSFULLY';
export const RETRIEVE_STORE_DETAIL_SUCCESSFULLY =
  'RETRIEVE_STORE_DETAIL_SUCCESSFULLY';
export const RETRIEVE_STORE_DETAIL_FAILED = 'RETRIEVE_STORE_DETAIL_FAILED';
