export const RETRIEVE_BRANCH_DETAIL_SUCCESSFULLY =
  'RETRIEVE_BRANCH_DETAIL_SUCCESSFULLY';
export const RETRIEVE_BRANCH_DETAIL_FAILED = 'RETRIEVE_BRANCH_DETAIL_FAILED';
export const SET_CURRENT_BRANCH = 'SET_CURRENT_BRANCH';
